### ISSUE TITLE
handling of model associations in an import?

### ISSUE THREAD

**Issue by b1tw1se** [BrewhouseTeam/csv-importer#28]
I'm using cvs-importer to import hardware details.. lets say:

model Host

And that model has a has_many :mac_addresses relationship.

Is it possible to perform an update/create for the corresponding MacAddress entries from a column in the CSV?

**Comment by pcreux** [comment]
Sure thing. Assuming you want to create / update the first record the following should do:

```ruby
column :mac, to: ->(mac, host) do
  mac_address = host.mac_adresses.first || host.mac_adresses.build
  mac_address.address = mac
end
```

You might have to set activerecord to autosave the association to update it. http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html

**Comment by b1tw1se** [comment]
awesome thanks!

**Comment by sshaw** [comment]
How would one handle looking up an association based on multiple columns/attributes?

I see 2 options: 

1. Use a PORO and/or model proxy that stored these attributes then looked up the association in `after_build`
1. Use model then lookup association `after_build` using `csv_attributes`


`csv_attributes` is not great since it's keys are not normalized. 

Maybe a good 3rd option would be: 

```rb
column %w[foo bar baz], :to => -> (columns, model)  {
  model.relation.find_or_initialze_by(:a => columns[:foo], :b => columns[:bar], :c => columns[:baz])
  # or similar
}
```
